ALTER TABLE IF EXISTS usuarios
  ADD COLUMN IF NOT EXISTS es_tutor BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE IF EXISTS usuarios
  ADD COLUMN IF NOT EXISTS tutor_grado TEXT;

ALTER TABLE IF EXISTS usuarios
  ADD COLUMN IF NOT EXISTS tutor_seccion TEXT;

